CREATE TABLE "subscription_plans" (
	"id" serial PRIMARY KEY NOT NULL,
	"plan_code" varchar(50) NOT NULL,
	"plan_name" varchar(100) NOT NULL,
	"plan_description" text,
	"price" numeric NOT NULL,
	"billing_interval" varchar(20) NOT NULL,
	"trial_days" integer,
	"message_quota" integer,
	"features" jsonb,
	"stripe_price_id" text,
	"is_displayed" boolean DEFAULT true NOT NULL,
	"display_order" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"is_default" boolean DEFAULT false NOT NULL,
	"homepage" boolean DEFAULT false NOT NULL,
	"funnelkit_tag_ids" text,
	"funnelkit_list_ids" text,
	"funnelkit_tag_ids_remove" text,
	"funnelkit_list_ids_remove" text,
	"subscription_ended_tag" boolean DEFAULT false NOT NULL,
	CONSTRAINT "subscription_plans_plan_code_unique" UNIQUE("plan_code"),
	CONSTRAINT "subscription_plans_stripe_price_id_unique" UNIQUE("stripe_price_id")
);
